name: Update Windows Build Numbers

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Checkout Branch
        run: git branch autoupdate