name: Update Windows Build Numbers

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Who am I
        run: |
          git config user.name "DataForNerds AutoUpdater"
          git config user.email "noreply@datafornerds.io"
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Checkout Branch
        run: git branch autoupdate
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/mswin/GetWin10ReleaseIds.ps1
      - name: Commit the Changes
        run: git commit -m "Autoupdate of ms-mswin-buildnumbers json"
      - name: Push the Changes
        run: git push