name: Update Windows Build Numbers

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Checkout New Branch
        run: git checkout autoupdate
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/mswin/GetWin10ReleaseIds.ps1
