name: Update Windows Build Numbers

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get DateTime Stamp for Branch
        id: datetime
        run: echo "::set-output name=datetime::echo $(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Who am I
        run: |
          git config user.name "DataForNerds AutoUpdater"
          git config user.email "noreply@datafornerds.io"
      - name: Checkout AutoUpdate Branch and Bring into Sync
        run: |
          git fetch
          git checkout -b au/ms-mswin-buildnumbers-{{steps.datetime.output.datetime}}
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/mswin/GetWin10ReleaseIds.ps1
      - name: Commit the Changes
        run: git commit -am "Autoupdate of ms-mswin-buildnumbers json"
      - name: Push the Changes
        run: git push